### ISSUE TITLE
Step to checkout a specific repo

### ISSUE THREAD

**Issue by PPFerrari** [ClouDesire/circleci-orbs#16]
## Describe Request:
It would be nice to have a "checkout_repo" command, to download a specific repo and checkout on a specific branch

## Examples:

Usage in config.yml:
```yaml
- cloudesire/checkout_repo:
    name: myrepo
    branch: mybranch
```
